name: Scheduled merge
on: 
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: cli-config-custom-smtp
          fetch-depth: 0 
      - name: Merge Upstream
        run: | 
          git remote add -f upstream "https://github.com/supabase/supabase.git"
          git remote -v
          git branch --all
          git config --list
          git config --global user.name '2yla3vum4o'
          git config --global user.email '2yla3vum4o@users.noreply.github.com'
          git merge --no-ff upstream/master
          git push